services:
  api-dev:
    build:
      context: server/wfprev-api
      dockerfile: Dockerfile.local
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REPORT_GENERATOR_LAMBDA_URL: https://mock-lambda-url
      REPORT_GENERATOR_SERVICE_URL: http://mock-report-generator
      WFDM_BASE_URL: https://i1bcwsapi.nrs.gov.bc.ca/wfdm-document-management-api
    volumes:
      - ./server/wfprev-api/target:/app/target
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:17-3.4
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./wfprev.dump:/dump/wfprev.dump

  client:
    build:
      context: client/wfprev-war
      dockerfile: Dockerfile.local
    profiles:
      - dev
    ports:
      - "4200:8080"
    networks:
      - wfprev-network
    depends_on:
      api-dev:
        condition: service_started
      db:
        condition: service_healthy
